// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: transcription.proto

#include "transcription.pb.h"
#include "transcription.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace sigper {
namespace transcription {

static const char* AudioTranscription_method_names[] = {
  "/sigper.transcription.AudioTranscription/TranscribeAudio",
};

std::unique_ptr< AudioTranscription::Stub> AudioTranscription::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AudioTranscription::Stub> stub(new AudioTranscription::Stub(channel, options));
  return stub;
}

AudioTranscription::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_TranscribeAudio_(AudioTranscription_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>* AudioTranscription::Stub::TranscribeAudioRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>::Create(channel_.get(), rpcmethod_TranscribeAudio_, context);
}

void AudioTranscription::Stub::async::TranscribeAudio(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::sigper::transcription::AudioSegmentRequest,::sigper::transcription::TranscriptResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::sigper::transcription::AudioSegmentRequest,::sigper::transcription::TranscriptResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_TranscribeAudio_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>* AudioTranscription::Stub::AsyncTranscribeAudioRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>::Create(channel_.get(), cq, rpcmethod_TranscribeAudio_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>* AudioTranscription::Stub::PrepareAsyncTranscribeAudioRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>::Create(channel_.get(), cq, rpcmethod_TranscribeAudio_, context, false, nullptr);
}

AudioTranscription::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AudioTranscription_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< AudioTranscription::Service, ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>(
          [](AudioTranscription::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::sigper::transcription::TranscriptResponse,
             ::sigper::transcription::AudioSegmentRequest>* stream) {
               return service->TranscribeAudio(ctx, stream);
             }, this)));
}

AudioTranscription::Service::~Service() {
}

::grpc::Status AudioTranscription::Service::TranscribeAudio(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::sigper::transcription::TranscriptResponse, ::sigper::transcription::AudioSegmentRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sigper
}  // namespace transcription

