// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: transcription.proto
#ifndef GRPC_transcription_2eproto__INCLUDED
#define GRPC_transcription_2eproto__INCLUDED

#include "transcription.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace sigper {
namespace transcription {

class AudioTranscription final {
 public:
  static constexpr char const* service_full_name() {
    return "sigper.transcription.AudioTranscription";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Method for bidirectional stream transcription of audio
    // Sends audio binary data (16Khz mono PCM) and receives transcript back
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>> TranscribeAudio(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>>(TranscribeAudioRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>> AsyncTranscribeAudio(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>>(AsyncTranscribeAudioRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>> PrepareAsyncTranscribeAudio(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>>(PrepareAsyncTranscribeAudioRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Method for bidirectional stream transcription of audio
      // Sends audio binary data (16Khz mono PCM) and receives transcript back
      virtual void TranscribeAudio(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::sigper::transcription::AudioSegmentRequest,::sigper::transcription::TranscriptResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>* TranscribeAudioRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>* AsyncTranscribeAudioRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>* PrepareAsyncTranscribeAudioRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>> TranscribeAudio(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>>(TranscribeAudioRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>> AsyncTranscribeAudio(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>>(AsyncTranscribeAudioRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>> PrepareAsyncTranscribeAudio(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>>(PrepareAsyncTranscribeAudioRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void TranscribeAudio(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::sigper::transcription::AudioSegmentRequest,::sigper::transcription::TranscriptResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>* TranscribeAudioRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>* AsyncTranscribeAudioRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>* PrepareAsyncTranscribeAudioRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_TranscribeAudio_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Method for bidirectional stream transcription of audio
    // Sends audio binary data (16Khz mono PCM) and receives transcript back
    virtual ::grpc::Status TranscribeAudio(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::sigper::transcription::TranscriptResponse, ::sigper::transcription::AudioSegmentRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_TranscribeAudio : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_TranscribeAudio() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_TranscribeAudio() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TranscribeAudio(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::sigper::transcription::TranscriptResponse, ::sigper::transcription::AudioSegmentRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTranscribeAudio(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::sigper::transcription::TranscriptResponse, ::sigper::transcription::AudioSegmentRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_TranscribeAudio<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_TranscribeAudio : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_TranscribeAudio() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->TranscribeAudio(context); }));
    }
    ~WithCallbackMethod_TranscribeAudio() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TranscribeAudio(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::sigper::transcription::TranscriptResponse, ::sigper::transcription::AudioSegmentRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::sigper::transcription::AudioSegmentRequest, ::sigper::transcription::TranscriptResponse>* TranscribeAudio(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_TranscribeAudio<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_TranscribeAudio : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_TranscribeAudio() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_TranscribeAudio() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TranscribeAudio(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::sigper::transcription::TranscriptResponse, ::sigper::transcription::AudioSegmentRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_TranscribeAudio : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_TranscribeAudio() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_TranscribeAudio() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TranscribeAudio(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::sigper::transcription::TranscriptResponse, ::sigper::transcription::AudioSegmentRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTranscribeAudio(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_TranscribeAudio : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_TranscribeAudio() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->TranscribeAudio(context); }));
    }
    ~WithRawCallbackMethod_TranscribeAudio() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TranscribeAudio(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::sigper::transcription::TranscriptResponse, ::sigper::transcription::AudioSegmentRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* TranscribeAudio(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace transcription
}  // namespace sigper


#endif  // GRPC_transcription_2eproto__INCLUDED
